export const ACTIVITY_MODEL = {
  ASSET: 'ASSET',
  AWARD: 'AWARD',
  GALLERY: 'GALLERY',
  LOCATION: 'LOCATION',
  POINT: 'POINT',
  PRODUCT: 'PRODUCT',
  ROLE: 'ROLE',
  USE_LOCATION: 'USE_LOCATION',
  USER: 'USER',
  VERIFICATION: 'VERIFICATION',
  EMAIL_TEMPLATE: 'EMAIL_TEMPLATE',
  REWARD: 'REWARD'
};

export const ACTIVITY_TYPE = {
  CREATE: 'CREATE',
  UPDATE: 'UPDATE',
  DELETE: 'DELETE',
  CHECKIN: 'CHECKIN',
  SIGNUP: 'SIGNUP',
  LOGIN: 'LOGIN',
  GET: 'GET',
  VIEW: 'VIEW'
};

export const STATUS_MSG = {
  SUCCEED: 'succeed',
  FAILED: 'failed'
};
