export const ACTIVITY_MODEL = {
  ASSET: 'ASSET',
  GALLERY: 'GALLERY',
  LOCATION: 'LOCATION',
  POINT: 'POINT',
  PRODUCT: 'PRODUCT',
  ROLE: 'ROLE',
  USE_LOCATION: 'USE_LOCATION',
  USER: 'USER',
  TABLET: 'TABLET',
  VERIFICATION: 'VERIFICATION',
  EMAIL_TEMPLATE: 'EMAIL_TEMPLATE',
  REWARD: 'REWARD',
  TRANSACTION: 'TRANSACTION',
  CAMPAIGN: 'CAMPAIGN'
};

export const ACTIVITY_TYPE = {
  CREATE: 'CREATE',
  UPDATE: 'UPDATE',
  DELETE: 'DELETE',
  CHECKIN: 'CHECKIN',
  SIGNUP: 'SIGNUP',
  LOGIN: 'LOGIN',
  GET: 'GET',
  VIEW: 'VIEW',
  REQUEST: 'REQUEST',
  ACCEPT: 'ACCEPT',
  DECLINE: 'DECLINE'
};

export const STATUS_MSG = {
  SUCCEED: 'succeed',
  FAILED: 'failed'
};
