export const CAMPAIGN_TYPE = {
  BIRTHDAY: 'BIRTHDAY',
  APPRECIATION: 'APPRECIATION',
  REFERRAL: 'REFERRAL',
  REWARDS: 'REWARDS',
  WELCOME: 'WELCOME',
  NEWSLETTER: 'NEWSLETTER'
};

export const CAMPAIGN_MODEL = {
  AUTO_PILOT: 'AUTO_PILOT',
  ON_DEMAND: 'ON_DEMAND',
  INFORMATIONAL: 'INFORMATIONAL'
};

export const CAMPAIGN_CHANNELS = {
  EMAIL: 1,
  PHONE: 2,
  BOTH: 3
};
