export const EMAIL_TEMPLATE_MAPPER = {
  VERIFY_EMAIL_FORGOT_PASSWORD: 'VERIFY_EMAIL_FORGOT_PASSWORD',
  CONFIRM_EMAIL_RESET_PASSWORD: 'CONFIRM_EMAIL_RESET_PASSWORD',
  ADD_POINT_EMAIL: 'ADD_POINT_EMAIL',
  ACCEPT_TRANSACTION_EMAIL: 'ACCEPT_TRANSACTION_EMAIL',
  DECLINE_TRANSACTION_EMAIL: 'DECLINE_TRANSACTION_EMAIL',
  REQUEST_TRANSACTION_EMAIL: 'REQUEST_TRANSACTION_EMAIL'
};

export const EMAIL_TEMPLATE_STATUS = {
  PENDING: 'PENDING',
  PUBLISHED: 'PUBLISHED',
  ARCHIVED: 'ARCHIVED'
};

export const EMAIL_TEMPLATE_TYPE = { DEFAULT: 'DEFAULT', DYNAMIC: 'DYNAMIC' };
