export const EMAIL_TEMPLATE_CATEGORY = {
  CONFIRM_USER_REGISTER: 'CONFIRM_USER_REGISTER',
  VERIFY_FORGOT_PASSWORD: 'VERIFY_FORGOT_PASSWORD',
  CONFIRM_RESET_PASSWORD: 'CONFIRM_RESET_PASSWORD',
  FORCE_RESET_PASSWORD: 'FORCE_RESET_PASSWORD',
  ADD_POINT: 'ADD_POINT',
  ACCEPT_TRANSACTION: 'ACCEPT_TRANSACTION',
  DECLINE_TRANSACTION: 'DECLINE_TRANSACTION',
  REQUEST_TRANSACTION: 'REQUEST_TRANSACTION'
};

export const EMAIL_TEMPLATE_STATUS = {
  PENDING: 'PENDING',
  PUBLISHED: 'PUBLISHED',
  ARCHIVED: 'ARCHIVED'
};

export const EMAIL_TEMPLATE_TYPE = { DEFAULT: 'DEFAULT', DYNAMIC: 'DYNAMIC' };

export const HASH_CODE_MODEL = {
  ACTIVITY: 'ACTIVITY',
  USER: 'USER',
  CONFIG: 'CONFIG',
  EMAIL_TEMPLATE: 'EMAIL_TEMPLATE',
  ASSET: 'ASSET',
  GALLERY: 'GALLERY',
  LOCATION: 'LOCATION',
  POINT: 'POINT',
  PRODUCT: 'PRODUCT',
  ROLE: 'ROLE',
  USE_LOCATION: 'USE_LOCATION',
  TABLET: 'TABLET',
  VERIFICATION: 'VERIFICATION',
  REWARD: 'REWARD',
  TRANSACTION: 'TRANSACTION'
};

export const EMAIL_SPECIAL_FIELD = {
  LINK: 'link',
  TOTAL_POINT: 'total_point'
};
