export const AUTH_ACTION_TYPE_MAPPER = {
  SET_USERNAME: 'SET_USERNAME',
  VERIFY_EMAIL: 'VERIFY_EMAIL',
  VERIFY_PHONE: 'VERIFY_PHONE',
  SET_TWO_FACTOR: 'SET_TWO_FACTOR',
  NOT_AVAILABLE: 'NOT_AVAILABLE'
};

export const USER_STATUS_MAPPER = {
  ACTIVATED: 'ACTIVATED',
  DISABLED: 'DISABLED',
  ARCHIVED: 'ARCHIVED',
  VERIFY_PHONE: 'VERIFY_PHONE',
  VERIFY_EMAIL: 'VERIFY_EMAIL'
};

export const ROLE_SHORT_CODES = {
  GUEST: 'GUEST',
  USER: 'USER',
  TABLET: 'TABLET',
  ADMIN: 'ADMIN',
  SUPER: 'SUPER'
};

export const USER_ROLE_MAPPER = {
  GUEST: 1,
  USER: 2,
  TABLET: 3,
  ADMIN: 4,
  SUPER: 5
};

export const USER_FILTER_TYPE_MAPPER = {
  ALL: 'ALL',
  ADMIN_USER: 'ADMIN',
  CUSTOMER_USER: 'CUSTOMER',
  TABLET_USER: 'TABLET',
  ARCHIVED_USER: 'ARCHIVED',
  ACTIVE_USER: 'ACTIVATED',
  DISABLED_USER: 'DISABLED'
};

export const DEFAULT_COUPON = 10000;

export const TEST_PHONE_NUMBER = [
  1234567890, 1112223333, 2223334444, 3334445555, 4445556666, 5556667777, 6667778888, 7778889999
];
