export const AUTH_ACTION_TYPE_MAPPER = {
  SET_USERNAME: 'SET_USERNAME',
  VERIFY_EMAIL: 'VERIFY_EMAIL',
  VERIFY_HUMAN: 'VERIFY_HUMAN',
  SET_TWO_FACTOR: 'SET_TWO_FACTOR',
  NOT_AVAILABLE: 'NOT_AVAILABLE'
};

export const USER_STATUS_MAPPER = {
  ACTIVATED: 'ACTIVATED',
  DISABLED: 'DISABLED',
  ARCHIVED: 'ARCHIVED',
  VERIFY_PHONE: 'VERIFY_PHONE'
};

export const ROLE_SHORT_CODES = {
  GUEST: 'GUEST',
  USER: 'USER',
  TABLET: 'TABLET',
  ADMIN: 'ADMIN',
  SUPER: 'SUPER'
};

export const USER_ROLE_MAPPER = {
  GUEST: 1,
  USER: 2,
  TABLET: 3,
  ADMIN: 4,
  SUPER: 5
};

export const USER_FILTER_TYPE_MAPPER = {
  ALL: 'ALL',
  ADMIN_USER: 'ADMIN_USER',
  GUEST_USER: 'GUEST_USER',
  TABLET: 'TABLET',
  ARCHIVED_USER: 'ARCHIVED_USER',
  ACTIVE_USER: 'ACTIVE_USER',
  DISABLED_USER: 'DISABLED_USER'
};
