export const VERIFICATION_TYPE_MAPPER = {
  VERIFY_PHONE: 'VERIFY_PHONE',
  VERIFY_EMAIL: 'VERIFY_EMAIL',
  INVITATION: 'INVITATION',
  FORGOT_PASSWORD: 'FORGOT_PASSWORD'
};

export const VERIFICATION_STATUS_MAPPER = {
  ACTIVATED: 'ACTIVATED',
  EXPIRED: 'EXPIRED',
  VERIFIED: 'VERIFIED',
  COMPLETED: 'COMPLETED'
};

export const INVITATION_STATUS_MAPPER = {
  ALL: 'ALL',
  ACTIVATED: 'ACTIVATED',
  EXPIRED: 'EXPIRED'
};
