Project EliteGame {
  database_type: 'PostgreSQL'
  note: '''
  # EliteGame BE
  '''
}

Enum user_status {
  ACTIVATED
  DISABLED
  ARCHIVED
  VERIFY_PHONE
  VERIFY_EMAIL
}

Table users [note: 'user table'] {
  id int [pk, increment]
  first_name varchar [note: 'first name']
  last_name varchar [note: 'last name']
  user_name varchar [unique, note: 'userid']
  email varchar
  phone varchar
  password varchar
  location "jsonb" [note: 'country, city, state, zipcode, address1, address2']
  birthday date
  asset_id int
  status user_status
  role_id int [not null, note: 'role id']
  created_at timestamp [default: `now()`]
  updated_at timestamp 
}

Ref: users.id < user_locations.user_id

Enum role_short_code {
  GUEST
  CUSTOMER
  TABLET
  ADMIN
  SUPER
}

Table roles [note: 'user role table'] {
  id int [pk, increment]
  name varchar
  short_code role_short_code
  created_at timestamp [default: `now()`]
  updated_at timestamp 
}

Ref: roles.id < users.role_id

Enum asset_type {
  IMAGE
  PDF
  VIDEO
}

Table assets [note: 'Application assets'] {
  id int [pk, increment]
  name varchar
  desc varchar
  url varchar
  type asset_type
  created_at timestamp [default: `now()`]
  updated_at timestamp 
}

Ref: assets.id < users.asset_id

Enum verification_type {
  VERIFY_EMAIL
  VERIFY_PHONE
  INVITATION
  FORGOT_PASSWORD
}

Enum verification_status {
  ACTIVATED
  EXPIRED
  VERIFIED
  COMPLETED
}

Table verifications [note: 'User verification'] {
  id int [pk, increment]
  victim_id int [note: 'action model id => user, invitation']
  type verification_type
  token varchar
  status verification_status
  created_at timestamp [default: `now()`]
  updated_at timestamp 
}

Table email_templates [note: 'email tempalte list'] {
  id int [pk, increment]
  name varchar
  subject varchar
  body varchar
  use_for varchar
  created_at timestamp [default: `now()`]
  updated_at timestamp 
}

Enum location_status {
  OPEN
  CLOSED
}

Enum location_type {
  PALM
  ROULETTE
}

Table locations [note: 'location table'] {
  id int [pk, increment]
  name varchar
  coords jsonb [note: 'lng, lat']
  status location_status
  address "jsonb" [note: 'country, city, state, zipcode, address1, address2']
  type location_type
  description varchar
  created_at timestamp [default: `now()`]
  updated_at timestamp 
}

Ref: locations.id < user_locations.location_id

Table user_locations [note: 'user and location table'] {
  id int [pk, increment]
  user_id int
  location_id int
  created_at timestamp [default: `now()`]
  updated_at timestamp 
}

Enum gallery_model {
  PRODUCT
  LOCATION
}

Table gallery [note: 'assets gallery table'] {
  id int [pk, increment]
  asset_id int
  victim_id int
  model gallery_model
  created_at timestamp [default: `now()`]
  updated_at timestamp 
}

Ref: assets.id < gallery.asset_id

Table points [note: 'points table'] {
  id int [pk, increment]
  user_location_id int
  point int
  created_at timestamp [default: `now()`]
  updated_at timestamp
}

Ref: user_locations.id < points.user_location_id

Enum product_status {
  AVAILABLE
  DISABLED
  OUTOFSTOCK
}

Table products [note: 'products table'] {
  id int [pk, increment]
  name varchar
  location_id int
  amount int
  point int
  status product_status
  short varchar
  description varchar
  created_at timestamp [default: `now()`]
  updated_at timestamp
}

Ref: locations.id < products.location_id

Enum award_status {
  ACCEPTED
  DECLINED
  WAITING
}

Table awards [note: 'awards table'] {
  id int [pk, increment]
  user_location_id int
  product_id int
  assignee_id int
  status award_status
  note varchar
  created_at timestamp [default: `now()`]
  updated_at timestamp
}

Ref: user_locations.id < awards.user_location_id
Ref: products.id < awards.product_id
Ref: users.id < awards.assignee_id

Enum activity_type {
  CREATE
  UPDATE    
  DELETE
  AUTH  
}

Enum activity_model {
  ASSET
  AWARD
  GALLERY
  LOCATION
  POINT
  PRODUCT
  ROLE
  USE_LOCATION
  USER
  VERIFICATION
  EMAIL_TEMPLATE
}

Table activities [note: "activity table"] {
  id int [pk, increment]
  user_id int 
  victim_id int
  model activity_model
  type activity_type 
  metadata jsonb  
  created_at timestamp [default: `now()`]
  updated_at timestamp
}

Ref: users.id < activities.user_id

